import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { signIn } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "🍸 Prestige List",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul className="flex flex-row gap-3">
          <li>
            <Link href="/api/auth/signin">giris</Link>
          </li>
        </ul>
        {children}
      
      </body>
    </html>
  );
}
